language: go

go:
  - 1.x

before_install:
  - go get -t -v ./...
  - chmod +x ./scripts/cibuild.sh
  - chmod +x ./scripts/test.sh
  # Download ngrok
  - curl -sO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip $PWD/ngrok-stable-linux-amd64.zip
  - chmod +x $PWD/ngrok
  # Open ngrok tunnel
  - $PWD/ngrok authtoken $NGROK_AUTH
  - $PWD/ngrok http -bind-tls=true -region eu 8081 > /dev/null &
script:
  - ./scripts/cibuild.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
