version: "3"
services:
  app:
    container_name: GoSyncMyCalendars-app
    restart: always
    build: .
    ports:
      - "443:8080"
      - "8081:8081"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - ENDPOINT=${ENDPOINT}
      - SENTRY_DSN=${SENTRY_DSN}
      - ORIGIN=${ORIGIN}
      - RELEASE=${RELEASE}
      - ENVIRONMENT=${ENVIRONMENT}
      - API_ROOT=${API_ROOT}

  postgres:
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: GoSyncMyCalendars-db
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  db-data: