version: "3"
services:
  app:
    container_name: 'GoSyncMyCalendars-app'
    restart: always
    build: .
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - ENDPOINT=${ENDPOINT}
      - SENTRY_DSN=${SENTRY_DSN}
      - ORIGIN=${ORIGIN}
      - RELEASE=${RELEASE}
      - ENVIRONMENT=${ENVIRONMENT}
      - API_ROOT=${API_ROOT}
    networks:
      - docker-network
    loggin:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "GoSyncMyCalendars"
        awslogs-stream: "app"

  postgres:
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: 'GoSyncMyCalendars-db'
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - docker-network
    loggin:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "GoSyncMyCalendars"
        awslogs-stream: "db"

  nginx:
    container_name: 'nginx'
    depends_on:
      - app
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    volumes:
      - ./.nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/certs/letsencrypt-site:/usr/share/nginx/html
      - ~/certs/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - ~/certs/live/gosyncmycalendars.me/fullchain.pem:/etc/letsencrypt/live/gosyncmycalendars.me/fullchain.pem
      - ~/certs/live/gosyncmycalendars.me/privkey.pem:/etc/letsencrypt/live/gosyncmycalendars.me/privkey.pem
      - ~/certs/live/gosyncmycalendars.me/chain.pem:/etc/letsencrypt/live/gosyncmycalendars.me/chain.pem
    networks:
      - docker-network
    loggin:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "GoSyncMyCalendars"
        awslogs-stream: "nginx"

volumes:
  db-data:

networks:
  docker-network:
    driver: bridge